hugs.prefix=Hugs
hugs.player-not-found=The person you wanted to hug is not here...
hugs.cool-down=Slow down. A hug needs a little breathing room.
hugs.hug-self=You tried to comfort yourself with the unhealed pain. You tasted impermanence.
hugs.hug-entity=Hugged {0}!
hugs.hug-player=Hugged {0}!
hugs.hug-multiple=Hugged {0} of them!
hugs.hug-hugged={0} hugged you!
